version: '3.8'
services:

  psg:
    image: postgres:14.1-alpine
    container_name: suml_psg
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes: 
      - ./psg_data/data:/var/lib/postgresql/data
      - ./psg_data/scripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql